name: Deploy Infrastructure

on:
    pull_request:
        branches:
            - main
        paths:
            - 'infra/**'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    pull-requests: write

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Bicep Linter
              run: az bicep build --file ./infra/main.bicep

    validate:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: azure/login@v2
              name: Azure Login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - uses: azure/arm-deploy@v2
              name: Run preflight validation
              with:
                scope: 'resourcegroup'
                deploymentName: ${{ github.run_number }}
                resourceGroupName: ${{ secrets.AZURE_RG_NAME }}
                template: ./infra/main.bicep
                parameters: publisherName=${{ secrets.PUBLISHER_NAME }} publisherEmail=${{ secrets.PUBLISHER_EMAIL }}
                deploymentMode: Validate

    preview:
        needs: validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: azure/login@v2
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - uses: Azure/cli@v1
              name: Run what-if
              with:
                inlineScript: |
                    az deployment group what-if --resource-group ${{ secrets.AZURE_RG_NAME }} --template-file ./infra/main.bicep --parameters publisherName=${{ secrets.PUBLISHER_NAME }} publisherEmail=${{ secrets.PUBLISHER_EMAIL }}

    deploy:
        needs: preview
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - uses: actions/checkout@v4
            - uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - uses: azure/arm-deploy@v2
              name: Run preflight validation
              with:
                  scope: 'resourcegroup'
                  deploymentName: ${{ github.run_number }}
                  resourceGroupName: ${{ secrets.AZURE_RG_NAME }}
                  template: ./infra/main.bicep
                  parameters: publisherName=${{ secrets.PUBLISHER_NAME }} publisherEmail=${{ secrets.PUBLISHER_EMAIL }}
                  failOnStdErr: false 
